apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/your-repo.git
    targetRevision: HEAD
    path: user-service/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: medium
  syncPolicy:
    automated:
      prune: true
      selfHeal: true